config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root to: 'homes#top'
    get 'animes/search' => 'homes#search'
    get 'about' => 'homes#about'
    get 'user/mypage' => 'users#show'
    get 'user/edit' => 'users#edit'
    get 'user/confirm' => 'users#confirm'
    patch 'user/update' => 'users#update'
    patch 'user/quit' => 'users#quit'
    resources :animes, only: [:index, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create, :destroy] do
        resource :likes, only: [:create, :destroy]
      end
    end
  end

  devise_for :user, :skip => [:password], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :animes, only: [:show, :update]
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_for :admin, :skip => [:password, :registrations], controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :animes

  validates :name, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genre_list = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.new
      @genre_list = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_genre_form.html.erb
<% if genre.errors.any? %>
  <div class="form__error_explanation">
    <ul class="form__error-list">
      <% genre.errors.full_messages.each do |message| %>
        <li class="form__error-item"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form__field">
  <%= f.label :name, "ジャンル名", class: 'form__label' %>
  <%= f.text_field :name, class: 'form__imput' %>
  <%= f.submit "変更を保存", class: 'form__button-genre' %>
</div>

app/views/admin/genres/edit.html.erb
<div class="main">
  <h3 class="main__headline">ジャンル編集</h3>
  <%= form_with model:@genre, url:admin_genre_path, class: 'form', local: true do |f| %>
    <%= render 'admin/genres/genre_form', f: f, genre: @genre %>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="main">
  <h2 class="main__headline">ジャンル一覧</h2>
  <%= form_with model:@genre, url:admin_genres_path, class: 'form', local: true do |f| %>
    <%= render 'admin/genres/genre_form', f: f, genre: @genre %>
  <% end %>

  <table class="genre">
    <tbody>
      <tr class="retu">
        <th class="title">ジャンル</th>
      </tr>
      <% @genre_list.each do |genre| %>
        <tr>
          <td class="name"><%= genre.name %></td>
          <td class=""><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'link' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>