config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root to: 'homes#top'
    get 'animes/search' => 'homes#search'
    get 'about' => 'homes#about'
    get 'user/mypage' => 'users#show'
    get 'user/edit' => 'users#edit'
    get 'user/confirm' => 'users#confirm'
    patch 'user/update' => 'users#update'
    patch 'user/quit' => 'users#quit'
    resources :animes, only: [:index, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create, :destroy] do
        resource :likes, only: [:create, :destroy]
      end
    end
  end

  devise_for :user, :skip => [:password], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :animes, only: [:show, :update]
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_for :admin, :skip => [:password, :registrations], controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  attachment :icon

  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @user_list = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :is_active)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="main">
  <h2 class="main__headline"><%= @user.name %>さんの会員情報編集</h2>
  <%= form_with model:@user, url:admin_user_path(@user.id), class: 'form', local:true do |f| %>
    <% if @user.errors.any? %>
      <div class="form__error_explanation">
        <ul class="form__error-list">
          <% @user.errors.full_messages.each do |message| %>
            <li class="form__error-item"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form__group">
      <div class="form__group-id">ユーザID</div>
      <div class="form__group-num"><%= @user.id %></div>
    </div>

    <div class="form__field">
      <%= f.label :name, "ユーザ名", class: 'form__label' %>
      <%= f.text_field :name, autofocus: true, class: 'form__imput' %>
    </div>

    <div class="form__field">
      <%= f.label :email, "メールアドレス", class: 'form__label' %>
      <%= f.email_field :email, autocomplete: "email", class: 'form__imput' %>
    </div>

    <div class="form__field">
      <%= f.label :introduction, "自己紹介", class: 'form__label' %>
      <%= f.text_area :introduction, rows: '5', class: 'form__imput' %>
    </div>

    <div class="form__field">
      <%= f.label :is_active, "会員ステータス", class: 'form__label' %>
      <div class='form__imput'>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "有効", value: :true %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "退会", value: :false %>
      </div>
    </div>

    <div class="form__actions">
      <div class="form__submit">
        <%= f.submit "変更保存", class: 'form__button' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="main">
  <h2 class="main__headline">会員一覧</h2>
  <table class="profile">
    <thead>
      <td class="profile__title">ユーザID</td>
      <td class="profile__title">ユーザ名</td>
      <td class="profile__title">メールアドレス</td>
      <td class="profile__title">ステータス</td>
    </thead>
    <tbody>
      <% @user_list.each do |user| %>
        <tr>
          <td class="profile__item"><%= user.id %></td>
          <td class="profile__item"><%= link_to user.name, admin_user_path(user.id), class: 'profile__link' %></td>
          <td class="profile__item"><%= user.email %></td>
          <td class="profile__item">
            <% if user.is_active %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class="main">
  <h2 class="main__headline"><%= @user.name %>さんの会員詳細情報</h2>
  <table class="profile">
    <tbody>
      <tr>
        <th class="profile__title">ユーザID</th>
        <td class="profile__item"><%= @user.id %></td>
      </tr>
      <tr>
        <th class="profile__title">ユーザ名</th>
        <td class="profile__item"><%= @user.name %></td>
      </tr>
      <tr>
        <th class="profile__title">メールアドレス</th>
        <td class="profile__item"><%= @user.email %></td>
      </tr>
      <tr>
        <th class="profile__title">自己紹介文</th>
        <td class="profile__item"><%= @user.introduction %></td>
      </tr>
      <tr>
        <th class="profile__title">ステータス</th>
        <td class="profile__item">
          <% if @user.is_active %>
            有効
          <% else %>
            退会
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="profile__edit-link">
    <%= link_to "ユーザ情報編集", edit_admin_user_path(@user.id), class: 'link' %>
  </div>
</div>