config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root to: 'homes#top'
    get 'animes/search' => 'homes#search'
    get 'about' => 'homes#about'
    get 'user/mypage' => 'users#show'
    get 'user/edit' => 'users#edit'
    get 'user/confirm' => 'users#confirm'
    patch 'user/update' => 'users#update'
    patch 'user/quit' => 'users#quit'
    resources :animes, only: [:index, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create, :destroy] do
        resource :likes, only: [:create, :destroy]
      end
    end
  end

  devise_for :user, :skip => [:password], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :animes, only: [:show, :update]
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_for :admin, :skip => [:password, :registrations], controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :comments, dependent: :destroy

  attachment :image

  acts_as_taggable

  validates :name, presence: true
  validates :genre, presence: true
  validates :image, presence: true
  validates :quote, presence: true
  validates :quote_url, presence: true
  validates :introduction, presence: true

  def self.search(keyword)
    where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  has_many :likes, dependent: :destroy

  validates :comment, presence: true

  # Likesテーブルにuserが存在するか
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :animes

  validates :name, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  attachment :icon

  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/animes_controller.rb
class Admin::AnimesController < ApplicationController
  before_action :authenticate_admin!
  def show
    @anime = Anime.find(params[:id])
    @comments = @anime.comments
  end

  def update
    @anime = Anime.find(params[:id])
    if @anime.is_active
      @anime.update(is_active: false)
    else
      @anime.update(is_active: true)
    end
    redirect_to admin_anime_path(@anime)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genre_list = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genre = Genre.new
      @genre_list = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @anime_list = Anime.all
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @user_list = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resourse)
    if admin_signed_in?
      # 管理者ログイン後
      admin_path
    else
      # ユーザログイン後,マイページへ遷移
      user_mypage_path
    end
  end

  def after_sign_out_path_for(resourse)
    if resourse == :admin
      # 管理者ログアウト後,ログイン画面へ遷移
      new_admin_session_path
    else
      # ユーザログアウト後,トップページへ遷移
      root_path
    end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/animes_helper.rb
module Admin::AnimesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_anime_show.html.erb
<div class="anime__image">
  <%= attachment_image_tag anime, :image, :fill, 200, 200 %>
  <div class="anime__image-quote">
    <div class="anime__quote">引用元：</div>
    <div class="anime__quote-link"><%= link_to anime.quote, anime.quote_url, class: 'anime__link-quote' %></div>
  </div>
</div>
<div class="anime__detail">
  <div>
    <h3 class="anime__detail-title">アニメタイトル</h3>
    <div class="anime__detail-item"><%= anime.name %></div>
  </div>
  <div>
    <h3 class="anime__detail-title">更新日</h3>
    <div class="anime__detail-item"><%= l anime.updated_at, format: :default %></div>
  </div>
  <div>
    <h3 class="anime__detail-title">ユーザ名</h3>
    <% if admin_signed_in? %>
      <div class="anime__detail-item"><%= link_to anime.user.name, admin_user_path(anime.user.id), class: 'genre-list__button' %></div>
    <% else %>
      <div class="anime__detail-item"><%= anime.user.name %></div>
    <% end %>
  </div>
  <div>
    <h3 class="anime__detail-title">ジャンル</h3>
    <div class="anime__detail-item">
      <%= link_to anime.genre.name, root_path(genre_id: anime.genre.id), class: 'genre-list__button' %>
    </div>
  </div>
  <div>
    <h3 class="anime__detail-title">タグ</h3>
    <div class="anime__detail-item">
      <% anime.tag_list.each do |tag| %>
        <%= link_to tag, root_path(tag_name: tag), class: 'anime__tag-item' %>
      <% end %>
    </div>
  </div>
  <div>
    <h3 class="anime__detail-title">推しポイント／魅力</h3>
    <div class="anime__detail-item"><%= anime.introduction %></div>
  </div>

  <% if admin_signed_in? %>
    <div>
      <h3 class="anime__detail-title">ステータス</h3>
      <div class="anime__detail-item">
        <% if anime.is_active %>
          <div>公開中</div>
          <%= link_to "公開しない", admin_anime_path(anime.id), method: :patch, class: 'anime__change-status' %>
        <% else %>
          <div>非公開</div>
          <%= link_to "公開する", admin_anime_path(anime.id), method: :patch, class: 'anime__change-status' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @anime.user == current_user %>
    <div>
      <h3 class="anime__detail-title">ステータス</h3>
      <div class="anime__detail-item">
        <% if anime.is_active %>
          <div>公開中</div>
        <% else %>
          <div>非公開</div>
        <% end %>
      </div>
    </div>
    <div class="form__actions">
      <%= link_to "編集する", edit_anime_path(@anime), class: 'link' %>
    </div>
  <% end %>
</div>

app/views/layouts/_comment_show.html.erb
<% if comments == [] %>
  <div class="anime__no-anime">コメントはありません</div>
<% end %>
<% comments.each do |comment| %>
  <div class="comment__list-item">
    <div class="comment__item-icon">
      <%= attachment_image_tag comment.user, :icon, :fill, 60, 60, fallback: 'no_user_image.jpg', class: 'comment__icon' %>
    </div>
    <div class="comment__item-info">
      <div class="comment__item-user">
        <%= link_to comment.user.name, admin_user_path(comment) , class: 'comment__link-user' %>
        <span class="anime__info-user"><%= l comment.created_at, format: :short %></span>
      </div>
      <div class="comment__item-comment">
        <%= comment.comment %>
      </div>

      <% if admin_signed_in? %>
        <div class="comment__item-likes">♡<%= comment.likes.count %></div>
      <% else %>
        <div id="likes_buttons_<%= comment.id %>">
          <%= render 'public/likes/like', anime: anime, comment: comment %>
        </div>
      <% end %>

      <% if comment.user == current_user || admin_signed_in? %>
        <div class="comment__delete-button">
          <%= link_to "削除する", anime_comment_path(comment.anime, comment), method: :delete, class: 'profile__confirm-yes' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anisite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8d0a097f97.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__inner">
        <h1 class="header__logo"><%= link_to "推しアニ", "/", class: 'header__logo-link' %></h1>
        <div class="header__nav">
          <ul class="header__nav-list">
            <% if admin_signed_in? %>
              <li class="header__nav-item">
                <%= link_to "初めての方へ", about_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "アニメ一覧", admin_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "会員一覧", admin_users_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'header__link' %>
              </li>
            <% elsif user_signed_in? %>
              <li class="header__nav-item">
                [<%= current_user.name %>]でログイン中
              </li>
              <li class="header__nav-item">
                <%= link_to "初めての方へ", about_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "マイページ", user_mypage_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "投稿アニメ一覧", animes_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'header__link' %>
              </li>
            <% else %>
              <li class="header__nav-item">
                <%= link_to "このサイトについて", about_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'header__link' %>
              </li>
              <li class="header__nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'header__link' %>
              </li>
            <% end %>
          </ul>
          <%= form_with url:animes_search_path, method: :get, local: true do |f| %>
            <div class="header__search">
              <%= f.text_field :keyword, value: @keyword, class: 'header__text' %>
              <%= button_tag type: :submit, class: 'header__button' do %>
                <i class="fas fa-search"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p class="footer-text">© All rights reserved by Infratop.Inc.</p>
    </footer>
  </body>
</html>